### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jiaozibufu** [0x33c0unt/process-based-proxy-redirection#1]
What is the compilation environment, I am using the Visual Studio 2019 version of the compiler

**Comment by 0x33c0unt** [comment]
Create an empty C++ project,  
1)Project->Add Existing Item-> Choose dllmain.cpp
2)Project->Properties->General->Configuration Type, Change it to .dll
3)Project->Properties->Advanced->Character set, Change to "Use Multi-Byte Character Set"
4)Project->Properties->C/C++->Preprocessor->Preprocessor Definitions, add ";_CRT_SECURE_NO_WARNINGS" to end of existing definitions or simply add "#define _CRT_SECURE_NO_WARNINGS" on the top of dllmain.cpp
5)Build
